name: Build and push Rover GitHub Agent to Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - blinq-main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: azlz-blinq-services-acr

    steps:
    - uses: actions/checkout@v4
    - name: Source config
      run: |
        $GITHUB_WORKSPACE/.github/workflows/scripts/persist-env.sh $GITHUB_WORKSPACE/.github/config/config.cfg

    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUB_MANAGEMENT }}
        allow-no-subscriptions: true

    - name: Build the rover
      run: |
        docker build -f agents/github/Dockerfile . \
            --build-arg versionGithubRunner=${version_github_runner} \
            --build-arg versionRover="${rover_repo}:${version_rover}" \
            --build-arg TARGETARCH=amd64 \
            --build-arg TARGETOS=linux \
            -t blinqas/rover-agent:${version_rover}-github-${version_github_runner} \
            -t blinqas/rover-agent:latest
            
    - name: Push the rover to Azure Container Registry
      run: |
        az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY }}
        docker tag blinqas/rover-agent:${version_rover}-github-${version_github_runner} ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/blinqas/rover-agent:${version_rover}-github-${version_github_runner}
        docker tag blinqas/rover-agent:latest ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/blinqas/rover-agent:latest
        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/blinqas/rover-agent:${version_rover}-github-${version_github_runner}
        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/blinqas/rover-agent:latest
    